headersOrigin = "config"
redirectsOrigin = "config"
functionsDirectory = "/Users/michaelsabatini/Documents/sorella-home-solutions/netlify/functions"
functionsDirectoryOrigin = "config"

[functions]

[functions."*"]

[[plugins]]
origin = "default"
package = "@netlify/angular-runtime"
pinned_version = "2"

[plugins.inputs]

[build]
publish = "/Users/michaelsabatini/Documents/sorella-home-solutions/dist/sorella-home-solutions/browser"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "/Users/michaelsabatini/Documents/sorella-home-solutions/netlify/functions"

[build.environment]
NODE_VERSION = "20"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/home-page-hero-video4-web-compressed.mp4"

[headers.values]
Content-Type = "video/mp4"
Cache-Control = "public, max-age=3600"
Accept-Ranges = "bytes"
Access-Control-Allow-Origin = "*"

[[headers]]
for = "/home-page-hero-v*.mp4"

[headers.values]
Content-Type = "video/mp4"
Cache-Control = "public, max-age=604800"
Accept-Ranges = "bytes"
Access-Control-Allow-Origin = "*"

[[headers]]
for = "/*.mp4"

[headers.values]
Content-Type = "video/mp4"
Cache-Control = "public, max-age=3600"
Accept-Ranges = "bytes"
Access-Control-Allow-Origin = "*"

[[redirects]]
from = "/home-page-hero-video4-web-compressed.mp4"
to = "/home-page-hero-video4-web-compressed.mp4"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*.mp4"
to = "/:splat.mp4"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*.jpg"
to = "/:splat.jpg"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*.png"
to = "/:splat.png"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*.svg"
to = "/:splat.svg"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*.css"
to = "/:splat.css"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*.js"
to = "/:splat.js"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*.ico"
to = "/:splat.ico"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/services-img/*"
to = "/services-img/:splat"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]