[build]
  publish = "dist/sorella-home-solutions/browser"
  command = "npm run build"

# SPA routing - serve index.html for all routes
# Netlify will automatically serve static files that exist before applying this rule
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"