[build]
  publish = "dist/sorella-home-solutions/browser"
  command = "npm run build"

# Disable function routing for static assets
[functions]
  directory = "netlify/functions"

# Static assets - must be served directly, NOT through functions
[[redirects]]
  from = "/home-page-hero-video4-web-compressed.mp4"
  to = "/home-page-hero-video4-web-compressed.mp4"
  status = 200
  force = true

[[redirects]]
  from = "/*.mp4"
  to = "/:splat.mp4"
  status = 200
  force = true

[[redirects]]
  from = "/*.jpg"
  to = "/:splat.jpg"
  status = 200
  force = true

[[redirects]]
  from = "/*.png"
  to = "/:splat.png"
  status = 200
  force = true

[[redirects]]
  from = "/*.svg"
  to = "/:splat.svg"
  status = 200
  force = true

[[redirects]]
  from = "/*.css"
  to = "/:splat.css"
  status = 200
  force = true

[[redirects]]
  from = "/*.js"
  to = "/:splat.js"
  status = 200
  force = true

[[redirects]]
  from = "/*.ico"
  to = "/:splat.ico"
  status = 200
  force = true

[[redirects]]
  from = "/services-img/*"
  to = "/services-img/:splat"
  status = 200
  force = true

# SPA routing - serve index.html for all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"